package constant

type ERROR_CODE string
type ERROR_MSG error

var (
	ERR_UNAUTHORIZED          ERROR_CODE = "ERR_UNAUTHORIZED"
	ERR_FORBIDDEN             ERROR_CODE = "ERR_FORBIDDEN"
	ERR_BAD_REQUEST           ERROR_CODE = "ERR_BAD_REQUEST"
	ERR_SERVICE_UNAVAILABLE   ERROR_CODE = "ERR_SERVICE_UNAVAILABLE"
	ERR_INTERNAL_SERVER_ERROR ERROR_CODE = "ERR_INTERNAL_SERVER_ERROR"
)
